name: release

on:
  workflow_dispatch:
    inputs:
      pre-release:
        description: |
          Marks the release as pre-release. Default false.
        type: boolean
        default: false
        required: false

permissions:
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}
          git-user-email: "41898282+github-actions[bot]@users.noreply.github.com"
          git-user-name: "github-actions[bot]"
          preset: "conventionalcommits"
          git-message: "release: {version}"
          version-file: "./custom_components/venta/manifest.json"
          skip-git-pull: "true"
          pre-release: "${{ github.event.inputs.pre-release }}"
          pre-release-identifier: "beta"
      - uses: ncipollo/release-action@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          prerelease: "${{ github.event.inputs.pre-release }}"
