name: hacs and homeassistant validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v3
      - name: hacs validation
        uses: hacs/action@main
        with:
          category: "integration"
      - name: hassfest validation
        uses: home-assistant/actions/hassfest@master
